[project]
name = "backend-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Alexis Lindsay", email = "alexislindsay@yahoo.com" }
]
requires-python = ">=3.12"
dependencies = [
    "google-antigravity>=0.1.9",
    "pydantic>=2.13.4",
    "python-dotenv>=1.2.2",
]

[project.scripts]
backend-agent = "backend_agent:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
